# EMPEZAR A PROGRAMAR
Esta es la primera clase

from pylab import*
%matplotlib inline

# Integer, Float y Doble

In [5]:
1./2

0.5

In [6]:
a = 1
b = 2
c = a/b

print c

0


In [8]:
b**2

4

In [9]:
b**3

8

In [10]:
sqrt(4)

2.0

In [11]:
4**(0.5)

2.0

# Vectores

In [20]:
vector1 = [1.,2.,3.,4.]

c = vector1 [2]/2

print c
print "La primera entrada es", vector1[0], "Lasegunda entreda es", vector1[1]

 1.5
La primera entrada es 1.0 Lasegunda entreda es 2.0


In [21]:
print vector1

[1.0, 2.0, 3.0, 4.0]


In [22]:
array([1.,2.,3.,4.])

array([ 1.,  2.,  3.,  4.])

In [24]:
a = ["hola", [1,2,3,], 507, 0.3]

In [25]:
a [0]

'hola'

In [26]:
zeros (5)

array([ 0.,  0.,  0.,  0.,  0.])

In [29]:
zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [34]:
vector2 = ones (8)

In [44]:
vector2 [0:5-1] = [11,12,13,14]
print vector2

[ 11.  12.  13.  14.   7.   7.   7.   7.]


In [45]:
vector3 = [1,2,3,4,5,6]
vector3 [2:4] = [11,12]
print vector3

[1, 2, 11, 12, 5, 6]


In [50]:
matriz1 = [[1,2,3,],[4,5,6],[7,8,9]]
print matriz1[1][2] 
print matriz1[1,2]

6


TypeError: list indices must be integers, not tuple

In [55]:
matriz2 = zeros((3,3))
matriz2[1,1] = 5.
print matriz2[1,1]
print matriz2

5.0
[[ 0.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0.  0.]]
